name: Nix build and push to Cachix
on:
  push:
    branches:
      - master
    paths:
      - 'nix/**'
      - '.github/workflows/**'
jobs:
  build:
    name: ${{ matrix.profile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [diraol-personal]
    steps:
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: ericdallo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: "Build ❄"
        run: |
          make build-${{ matrix.profile }} -C nix
