name: Build and push nix derivations to cachix
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gregnix-personal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: gregnix-personal
            token-name: CACHIX_AUTH_TOKEN_GREGNIX_PERSONAL
          - profile: gregnix-nubank
            token-name: CACHIX_AUTH_TOKEN_GREGNIX_NUBANK
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: ericdallo-${{ matrix.profile }}
          authToken: "${{ secrets[matrix.token-name] }}"
      - name: Build
        run: |
          cachix use ericdallo-${{ matrix.profile }}
          make build-${{ matrix.profile }} -C nix
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cachix push ericdallo-${{ matrix.profile }} ./result
