name: Nix build and push to cachix
on:
  push:
    branches:
      - master
  paths:
      - 'nix/**'
      - '.github/workflows/cachix-build.yml'
jobs:
  build:
    name: ${{ matrix.profile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: gregnix-personal
            token-name: CACHIX_AUTH_TOKEN_GREGNIX_PERSONAL
          - profile: gregnix-nubank
            token-name: CACHIX_AUTH_TOKEN_GREGNIX_NUBANK
    steps:
      - run: sudo rm -rf /opt&
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: ericdallo-${{ matrix.profile }}
          authToken: "${{ secrets[matrix.token-name] }}"

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: "Build ❄"
        run: |
          cachix use ericdallo-${{ matrix.profile }}
          make build-${{ matrix.profile }} -C nix
