name: Update flake.lock and push to Cachix
on:
  workflow_dispatch: null
  schedule:
    - cron: 40 4 * * 0,4
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: ericdallo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: "Update flake.lock ❄"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          make update-and-commit -C nix

      - name: "Build gregnix-personal ❄"
        run: |
          make build-gregnix-personal -C nix

      - name: "Build gregnix-nubank ❄"
        run: |
          make build-gregnix-nubank -C nix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          body: |
            ## Run report
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: flake-updates
          delete-branch: true
          title: Update flake.lock
